import { SelectOption } from './interfaces';

export const countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'British Virgin Islands',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Cape Verde',
    'Cayman Islands',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Congo',
    'Cook Islands',
    'Costa Rica',
    'Cote D Ivoire',
    'Croatia',
    'Cruise Ship',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Estonia',
    'Ethiopia',
    'Falkland Islands',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Polynesia',
    'French West Indies',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Kyrgyz Republic',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Nepal',
    'Netherlands',
    'Netherlands Antilles',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Reunion',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Pierre and Miquelon',
    'Samoa',
    'San Marino',
    'Satellite',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'St Kitts and Nevis',
    'St Lucia',
    'St Vincent',
    'St. Lucia',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    "Timor L'Este",
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'Uruguay',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Virgin Islands (US)',
    'Yemen',
    'Zambia',
    'Zimbabwe',
];

export class SelectOptions {
    constructor(public options: SelectOption[], private defaultValue: string) {}

    defaultOption(value: string = this.defaultValue): SelectOption {
        return this.options.find((o: SelectOption) => o.value === value);
    }
}

const amountCountries = new SelectOptions(
    [
        { value: '', title: 'Does not metter' },
        { value: '1', title: '1 country' },
        { value: '2', title: '2 countries' },
        { value: '3', title: '3 countries' },
        { value: '4-5', title: '4-5 countries' },
        { value: '6-7', title: '6-7 countries' },
        { value: '8-10', title: '8-10 countries' },
        { value: '10+', title: '11 or more' },
    ],
    '1'
);

const amountCities = new SelectOptions(
    [
        { value: '', title: 'Does not metter' },
        { value: '1', title: '1 city' },
        { value: '2', title: '2 cities' },
        { value: '3', title: '3 cities' },
        { value: '4-5', title: '4-5 cities' },
        { value: '6-7', title: '6-7 cities' },
        { value: '8-10', title: '8-10 cities' },
        { value: '10+', title: '11 or more' },
    ],
    '1'
);

const budget = new SelectOptions(
    [
        { value: '', title: 'Does not metter' },
        { value: '100', title: 'Up to 100$' },
        { value: '300', title: 'Up to 300$' },
        { value: '700', title: 'Up to 700$' },
        { value: '1500', title: 'Up to 1500$' },
        { value: '2000', title: 'Up to 2000$' },
        { value: '4000', title: 'Up to 4000$' },
        { value: '4000+', title: '4001 or more' },
    ],
    '300'
);

const category = new SelectOptions(
    [
        { value: 'amountCities', title: 'Amount of cities' },
        { value: 'people', title: 'Amount of travellers' },
        { value: 'author', title: 'Author' },
        { value: 'budget', title: 'Budget' },
        { value: 'city', title: 'City' },
        { value: 'continent', title: 'Continent' },
        { value: 'country', title: 'Country' },
        { value: 'duration', title: 'Trip duration' },
    ],
    'country'
);

const continent = new SelectOptions(
    [
        { value: '', title: 'Does not metter' },
        { value: 'Africa', title: 'Africa' },
        { value: 'Antarctica', title: 'Antarctica' },
        { value: 'Asia', title: 'Asia' },
        { value: 'Australia', title: 'Australia' },
        { value: 'Europe', title: 'Europe' },
        { value: 'North America', title: 'North America' },
        { value: 'South America', title: 'South America' },
    ],
    'Europe'
);

const country = new SelectOptions(
    [{ value: '', title: 'Does not metter' }].concat(
        countries.map((name) => ({
            value: name,
            title: name,
        }))
    ),
    'France'
);

const duration = new SelectOptions(
    [
        { value: '', title: 'Does not metter' },
        { value: '1', title: '1 day' },
        { value: '2-3', title: '2-3 days' },
        { value: '4-5', title: '4-5 days' },
        { value: '6-8', title: '6-8 days' },
        { value: '9-11', title: '9-11 days' },
        { value: '12-14', title: '12-14 days' },
        { value: '15+', title: '15 or more' },
    ],
    '2-3'
);

const people = new SelectOptions(
    [
        { value: '', title: 'Does not metter' },
        { value: '1', title: '1 person' },
        { value: '2', title: '2 people' },
        { value: '3', title: '3 people' },
        { value: '4', title: '4 people' },
        { value: '5', title: '5 people' },
        { value: '6-8', title: '6-8 people' },
        { value: '8+', title: '9 or more' },
    ],
    '2'
);

export const searchSelects = {
    amountCountries,
    amountCities,
    budget,
    category,
    continent,
    country,
    duration,
    people,
};
